### ISSUE TITLE
Add support for connection config files

### ISSUE THREAD

**Issue by swarley** [swarley/eviler-winrm#3]
Add in the ability to add files that effectively act as setting the command line arguments. Potentially a few more options like plugin loading and whatnot.

The files would be in json or yaml format and look something like
```yaml
ip: 10.10.10.10
user: foo
pass: bar
prompt: %{red}[foo@host] %{blue}(Get-Location)>%{default}
```
